name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  shellcheck:
    name: ShellCheck
    if: |
      github.event.pull_request != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: ASDF plugin test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: mint --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
